export const ACCEPT_INCIDENT_START = 'ACCEPT_INCIDENT_START';
export const ACCEPT_INCIDENT_SUCCESS = 'ACCEPT_INCIDENT_SUCCESS';
export const ACCEPT_INCIDENT_ERROR = 'ACCEPT_INCIDENT_ERROR';
export const REJECT_INCIDENT_START = 'REJECT_INCIDENT_START';
export const REJECT_INCIDENT_SUCCESS = 'REJECT_INCIDENT_SUCCESS';
export const REJECT_INCIDENT_ERROR = 'REJECT_INCIDENT_ERROR';
